version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
      #host:image
    volumes:
      - ./app:/app
    #  volumes allows project to use live update (when changing app in host will change app in image)
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"